#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

verify_app_name "$1"

if [[ -f "$DOKKU_ROOT/NOTIFY_URL" ]]; then
  echo "-----> Notifying ..."
  echo $APP
  URL=$(dokku url $APP)
  echo $URL
  NOTIFY_URL=$(cat "$DOKKU_ROOT/NOTIFY_URL" 2> /dev/null)
  NOTIFY_JSON="{ \
    \"deployed\": \"$URL\", \
    \"revision\": \"$2\"
  }"
  echo "       ${NOTIFY_JSON}"
  CURL_RESULT=$(curl -s -d "payload=$NOTIFY_JSON" "${NOTIFY_URL}" -w "%{http_code}" || echo "")
  echo "       ${CURL_RESULT}"
fi
